databases:
  - name: myfirstsite
    databaseName: myfirstsite
    user: myfirstsite

services:
  - type: web
    name: myfirstsite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myfirstsite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
